fix mail_config
failed on Travis: https://travis-ci.org/codeforamerica/streetmix/builds/35904113

    NameError: undefined local variable or method `config' for main:Object
    /home/travis/build/codeforamerica/streetmix/config/initializers/mail_config.rb:5:in `<top (required)>'